name : Linter
on:
  push:
    branches:
      - main

jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Make lint.sh executable
              run: chmod +x lint.sh
           
        
            - name: Run Linter
              run: ./lint.sh
